language: python
python:
- '3.6'
sudo: required
services:
- docker
install:
- pip install -r "./requirements.txt"
script:
- "./docker-images"
- docker ps -a
- docker images -a
env:
  global:
  - DOCKERHUB_USER="radioactiveradium226"
  - secure: j7ZGkwOM+vzZudge7VlChRjEk89hiSX5mFO8+H5JghzruVoJSN7GWkmkjkx7bGgOqg24kdgBjt3vhoO9UTr9uYP/zYLi9rEhb86C3Q9qqA4Ymcy5oYAPsk+ZIWbOcEEeloHhXusnlKl8fkOZKKjoooPsVDEr4jV+k35t3X/WFDelFfpq+aB6OYHZ60gTBWI+uYM86tkbKlZLHgDMVbd+hw52moe8WrjuAtJHjZO7CNXmcpXO/b4N3wiy6FJixX67j81pjJBXLauFRCrBDRX+FPBAXZYiLySnDVDE7poPttekeaGzLyv3QPkz2RIwD4IMV9co6jewFjmkWcuSQUwggXI7eIrYARmNcxsmowmvaeQ/Ich6mTeYfTfFXDZ/iqtzJ0cOBVh1s7imPULLXnjBo83WSP+hhQKJnhyRmZuBCmVvPCMLlgFuVl2AjLR+0H7RwsZ1Z63fRlD7PZnftdrPdoIfRDgIm8Jo5XGF8VutvLFzMwdMctfeVIudYlJS8y49OpH20xjZcy9p6O4lsGsTueFXGoBWy9dKyXimri7/HZE+C29yMYroRGF2BOAJJ/uoTv6j1/DMWqwfR98pmt/+kiUkOFobISQgfDV7WoGwyJrBvyVcZx3oF8rfjuo/ik86oGGxY2InieACYD7My61bAvglkZqvVVLuiekutWA6BtI=
