version: "2.2"
services:
  spark-master:
    build: "./master"
    ports:
      - 8080:8080
      - 7077
    volumes:
      - spark-events:/var/lib/spark/events
  spark-worker:
    build: "./worker"
    scale: 2
    volumes:
      - spark-events:/var/lib/spark/events
    depends_on:
      - spark-master
    ports:
      - 8081
    volumes:
      - spark-events:/var/lib/spark/events
  spark-history:
    build: "./history"
    ports:
      - 18080:18080
    volumes:
      - spark-events:/var/lib/spark/events

volumes:
  spark-events:
